package notker.blockgame_exp_hud;


public enum AttributeTags {
    NONE( "NoTag"),
    EXP_ARCHAEOLOGY("MMOITEMS_ADDITIONAL_EXPERIENCE_ARCHAEOLOGY"),
    EXP_FISHING("MMOITEMS_ADDITIONAL_EXPERIENCE_FISHING"),
    EXP_HERBALISM("MMOITEMS_ADDITIONAL_EXPERIENCE_HERBALISM"),
    EXP_LOGGING("MMOITEMS_ADDITIONAL_EXPERIENCE_LOGGING"),
    EXP_MINING("MMOITEMS_ADDITIONAL_EXPERIENCE_MINING"),
    EXP_RUNECARVING("MMOITEMS_ADDITIONAL_EXPERIENCE_RUNECARVING"),
    EXP_CLASS("MMOITEMS_ADDITIONAL_EXPERIENCE"),
    SKILL_LOGGING("MMOITEMS_SKILL_LOGGING"),
    SKILL_FISHING("MMOITEMS_SKILL_FISHING"),
    SKILL_HERBALISM("MMOITEMS_SKILL_HERBALISM"),
    SKILL_ARCHAEOLOGY("MMOITEMS_SKILL_ARCHAEOLOGY"),
    SKILL_MINING("MMOITEMS_SKILL_MINING"),
    PVP_DMG("MMOITEMS_PVP_DAMAGE"),
    PVP_DMG_REDUCTION("MMOITEMS_PVP_DAMAGE_REDUCTION"),
    PVE_DMG("MMOITEMS_PVE_DAMAGE"),
    PVE_DMG_REDUCTION("MMOITEMS_PVE_DAMAGE_REDUCTION");

    private final String tag;

    AttributeTags(String tag) {
        this.tag = tag;
    }

    public String tag() {
        return this.tag;
    }

}
